### ISSUE TITLE
Install error - asn1time.go undefined asn1.TagUTCTime

### ISSUE THREAD

**Issue by fishouttah20** [SSLMate/certspotter#15]
Trying to install certspotter on Ubuntu 15.10 with go 1.5.1 and getting:

go get software.sslmate.com/src/certspotter/cmd/certspotter
software.sslmate.com/src/certspotter
.go/src/software.sslmate.com/src/certspotter/asn1time.go:245: undefined: asn1.TagUTCTime
.go/src/software.sslmate.com/src/certspotter/asn1time.go:247: undefined: asn1.TagGeneralizedTime

I'm sure I'm doing something dumb, any ideas?

**Comment by AGWA** [comment]
Nope, this was my fault - I broke compatibility with Go 1.5 and didn't notice it.  Should work now, thanks for reporting.

**Comment by fishouttah20** [comment]
Good stuff, thanks. Once I figured out I needed to delete both src and pkg cache's in the gowork cache it installed fine. Thanks again!
