### ISSUE TITLE
Search pattern in -script 

### ISSUE THREAD

**Issue by gerhard-tinned** [SSLMate/certspotter#21]
When writing a script for the -script option, I noticed that there are many details about the CT and the certificate. I was wondering if there is a variable to identify the matching search therms from the watchlist. 

Example: I have multiple search terms in the watchlist. When I get a script call, I would like to know which search term was triggering it to trigger the correct actions in the script (e.g. notify the correct people, ...)

How could this be done? Is there a variable I did not see documented in Issue  #11.

**Comment by AGWA** [comment]
This is not currently possible, but I can see the utility.

To be clear, do you want to know which identifiers in the certificate matched, or do you want to know which watchlist entries matched? The former would be easier to implement.

**Comment by gerhard-tinned** [comment]
The watchlist entry (entries) would be the interesting information. The watchlist entry is the identifying information for the notification sent out.

**Comment by gerhard-tinned** [comment]
Is there any update for If and when this will be implemented?

**Comment by AGWA** [comment]
As of v0.15.0, certspotter sets `$WATCH_ITEM` containing the first item from the watch list which matched the certificate.
