### ISSUE TITLE
Remove StartCom/WoSign?

### ISSUE THREAD

**Issue by leonelwilliams** [SSLMate/certspotter#28]
These two logs seem to have been disqualified in Chrome at the very end of 2018-02-12:

- [WoSign](https://groups.google.com/a/chromium.org/forum/#!msg/ct-policy/UcCqlxuz_1c/Mf_939xYAQAJ)
- [StartCom](https://groups.google.com/a/chromium.org/forum/#!msg/ct-policy/W1Ty2gO0JNA/ZbQxlgRZAQAJ)

Should they be removed from certspotter now? Or is there a reason to keep monitoring them?

**Comment by AGWA** [comment]
If the logs remain up, then it makes sense to keep monitoring them in case they misbehave further.

However, it looks like they're both down now, so they'll be removed from certspotter shortly.

**Comment by leonelwilliams** [comment]
Ah I see. Thanks! :)
