### ISSUE TITLE
Overridden state_dir still requires ~/.certspotter/watchlist

### ISSUE THREAD

**Issue by konklone** [SSLMate/certspotter#4]
State will be stored in the value of `-state_dir`, but the watchlist is still sourced from `~/.certspotter/watchlist`:

```
$ certspotter -state_dir /opt/certspotter

certspotter: /home/ubuntu/.certspotter/watchlist: open /home/ubuntu/.certspotter/watchlist: no such file or directory
```

**Comment by AGWA** [comment]
That's correct.  The watchlist location is specified by the `-watchlist` option. (The watchlist is considered configuration, not state.)
