### ISSUE TITLE
Error retrieving STH from log: GET https://ctlog-gen2.api.venafi.com/ct/v1/get-sth: Parsing response JSON failed: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by adrelanos** [SSLMate/certspotter#42]
> certspotter: ctlog-gen2.api.venafi.com: 2020/09/17 16:38:59 Error retrieving STH from log: GET https://ctlog-gen2.api.venafi.com/ct/v1/get-sth: Parsing response JSON failed: invalid character '<' looking for beginning of value

**Comment by AGWA** [comment]
Please ensure you are using the latest version of Cert Spotter.
