### ISSUE TITLE
Error retrieving STH from log: GET https://ct2.digicert-ct.com/log/ct/v1/get-sth: 404 Not Found (not found)

### ISSUE THREAD

**Issue by adrelanos** [SSLMate/certspotter#43]
> certspotter: ct2.digicert-ct.com/log: 2020/09/17 16:39:05 Error retrieving STH from log: GET https://ct2.digicert-ct.com/log/ct/v1/get-sth: 404 Not Found (not found)

**Comment by AGWA** [comment]
Please ensure you are using the latest version of Cert Spotter.
