### ISSUE TITLE
Broken https://ct1.digicert-ct.com/log/ct/v1

### ISSUE THREAD

**Issue by semik** [SSLMate/certspotter#45]
Hi, I know this isn't exactly certstotter's problem, but I failed to find better place where to ask. 

At 12. 02. 21 7:06 CET I've started receiving errors:

`/usr/bin/certspotter: ct1.digicert-ct.com/log: 2021/02/12 06:36:15 Problem fetching entries 23910613 to 23910769 from log: GET https://ct1.digicert-ct.com/log/ct/v1/get-entries?start=23910613&end=23910769: Reading response failed: unexpected EOF`

I've discovered that by lowering second argument to 23910630 of URL https://ct1.digicert-ct.com/log/ct/v1/get-entries?start=23910613&end=23910630  is almost every time to download valid json. 

How to recover from this problem?

Thanks Jan

**Comment by AGWA** [comment]
This log seems to be working again as of Mon Feb 15 14:25:58 UTC 2021.  I haven't detected any other misbehavior of this log so certspotter should recover automatically.  I've asked DigiCert to provide an incident report here: https://groups.google.com/a/chromium.org/d/msgid/ct-policy/20210215110657.f74fc60e86c2abab82d26d42%40andrewayer.name
