### ISSUE TITLE
Getting timeout on https://loglist.certspotter.org/monitor.json

### ISSUE THREAD

**Issue by certrik** [SSLMate/certspotter#50]
./go/bin/certspotter: Error loading log list: Get https://loglist.certspotter.org/monitor.json: dial tcp 54.236.181.46:443: i/o timeout

**Comment by certrik** [comment]
@AGWA 
Please fix:
```
ERROR: The certificate of ‘loglist.certspotter.org’ is not trusted.
ERROR: The certificate of ‘loglist.certspotter.org’ has expired.
```

**Comment by AGWA** [comment]
Monitoring hasn't detected any problems with the network connectivity or certificate on loglist.certspotter.org, nor have I received any other reports of problems.  Possible explanations for the errors you are receiving:

* Your system is behind a middlebox which is causing timeouts and replacing the certificate with an untrusted one.
* Your system clock is incorrect.
* Your network is unreliable.

I don't believe there is a problem on my end that needs to be fixed.
