### ISSUE TITLE
add Message-ID Header

### ISSUE THREAD

**Issue by andreasschulze** [SSLMate/certspotter#82]
Messages are missing a Message-ID header [here](https://github.com/SSLMate/certspotter/blob/f8040df68d2af4bbdb5710c4ba24b828e168ab3a/monitor/notify.go#L69-L73)

Could consider adding one?

I think, somethine like
```
Message-ID: <$sha_of_cert@certspotter>
```
would be sufficient ([spec](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6.4))

**Comment by andreasschulze** [comment]
reading thh spec, it should be
```
Message-ID: <$sha_of_cert@certspotter.local>
```

the right part should better look like a domainname

**Comment by AGWA** [comment]
Would this solve a real-world problem? I would expect sendmail, as the MSA, to add the `Message-ID` field (https://datatracker.ietf.org/doc/html/rfc6409#section-8.3).

**Comment by andreasschulze** [comment]
good question: at least using [ssmtp](https://packages.debian.org/bookworm/ssmtp) I see messages without that header. Forwarding via an MTA that minimize message modifications (thus not adding headers) may fail ...

**Comment by andreasschulze** [comment]
OK, as you mentioned adding this header is an MSA's job I can't object if you close that ticket.  
On the other side it's always a good thing if any software generate well formed messages out of the box.

**Comment by andreasschulze** [comment]
tested and works ...
Thanks!
