### ISSUE TITLE
Monitoring of SAML IdP cert expirations

### ISSUE THREAD

**Issue by bdwilson** [SSLMate/certspotter#92]
Does this product have the ability to monitor expiration dates within SAML IdP metadata.xml files?  These are on public endpoints of identity providers and usually have self-signed certs, however those will have expirations.

**Comment by AGWA** [comment]
Hi @bdwilson, at present Cert Spotter only monitors certificates that are found on TLS endpoints or in Certificate Transparency logs, but monitoring certificates in SAML metadata files is definitely an idea we'll consider.
