### ISSUE TITLE
Can I use alternate email server to send an emails? 

### ISSUE THREAD

**Issue by Blason** [SSLMate/certspotter#94]
Hi Team,

I am using Google Apps and integration of sendmail with Google Apps is really a pin instead can I use alternate email client which will be very easy for integration with Google Apps? like sendEmail?

**Comment by AGWA** [comment]
You can customize the notification logic by placing a script in the `$CERTSPOTTER_CONFIG_DIR/hooks.d` directory (`~/.certspotter/hooks.d` by default), as documented in the [certspotter-script(8) manpage](https://github.com/SSLMate/certspotter/blob/master/man/certspotter-script.md).

**Comment by Blason** [comment]
How can we put custom command in script? I do not see that option
